export const PLAYER_ACTION = "PLAYER_ACTION";
export const BOT_ACTION = "BOT_ACTION";
export const NUMBER_TO_DIVIDE_BY_THREE = "NUMBER_TO_DIVIDE_BY_THREE";
export const TURN_COUNTER = "TURN_COUNTER";
export const INITIALIZE_GAME_PLAY = "INITIALIZE_GAME_PLAY";